### ISSUE TITLE
[Feature Request] Make the frontend SDK in Dart (Flutter)

### ISSUE THREAD

**Issue by Nightwing13** [TeamPiped/piped-rust-sdk#4]
Reasons
1. Dart is basically designed for UI. Which makes sense over using Rust(for some weird reason).
2. Flutter is cross-platform
3. Less performance compromise
4. Eliminates GTK quirkiness(Which is common in any language other than C and to an extent, C++)

**Comment by FireMasterK** [comment]
You could experiment with some OpenAPI code generators with https://github.com/TeamPiped/OpenAPI

For example, https://openapi-generator.tech/docs/generators/ supports Dart.

**Comment by Nightwing13** [comment]
Thanks.
